AWSTemplateFormatVersion: 2010-09-09
Description: |
   Cloudformation Template for kittens carousel static website deploy on s3 through cloudfront and route 53. 
Parameters:
  DomainName:
    Description: DNS Name of existing Amazon Route 53 hosted zone. exp. clarusway.us
    Type: AWS::Route53::HostedZone::Id
  KittensDomainName:
    Description: Full domain name for static website example. kittens.clarusway.us
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: Please write a subdomain name which has utmost 63 characters
Resources:
  KittensCarousel:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: PublicRead
      BucketName: !Ref KittensDomainName
      WebsiteConfiguration: 
        IndexDocument: index.html
  s3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref KittensCarousel
      PolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal: '*'
            # Resource: !Join
            #   - ''
            #   - - 'arn:aws:s3:::'
            #     - !Ref KittensCarousel
            #     - /*
            Resource: !Sub "${KittensCarousel.Arn}/*"
  KittensCertificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      CertificateTransparencyLoggingPreference: ENABLED 
      DomainName: !Ref KittensDomainName
      DomainValidationOptions:
        - DomainName: !Ref KittensDomainName
          HostedZoneId: !Ref DomainName
      ValidationMethod: DNS
  KittensCloudfront:
    Type: "AWS::CloudFront::Distribution" 
    Properties:
      DistributionConfig:
        Aliases:
        - !Ref KittensDomainName 
        Comment: Cloudfront Distribution pointing to Kittens S3 bucket
        DefaultCacheBehavior:
          AllowedMethods:  
          - GET
          - HEAD
          Compress: true
          ForwardedValues: 
            QueryString: true 
            Cookies:
              Forward: none 
          TargetOriginId: KittensOrigin  
          ViewerProtocolPolicy: allow-all 
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: 'http2'
        Origins: 
        - DomainName: !Select [2, !Split ["/", !GetAtt KittensCarousel.WebsiteURL]] 
          Id: KittensOrigin
          CustomOriginConfig: 
            OriginProtocolPolicy: http-only 
        PriceClass: PriceClass_All
        ViewerCertificate:  
          AcmCertificateArn: !Ref KittensCertificate
          SslSupportMethod: sni-only 
  route53RSGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref DomainName
      RecordSets: 
        - Name: !Ref KittensDomainName
          Type: A
          AliasTarget: 
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt KittensCloudfront.DomainName 
Outputs:
  BucketName: 
    Description: S3 Bucket URL for Kittens Website
    Value: !GetAtt KittensCarousel.WebsiteURL
  CloudfrontEndpoint:
    Description: Endpoint for Kittens Cloudfront
    Value: !GetAtt KittensCloudfront.DomainName
  FullDomainName:
    Description: Full Domain Name of my Application
    Value: !Ref KittensDomainName
Collapse



